//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.10 at 06:57:40 PM IST 
//


package com.alliance.schema.validation;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tables"
})
@XmlRootElement(name = "Database")
public class Database {

    @XmlElement(name = "Tables", required = true)
    protected Database.Tables tables;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "Schema")
    protected String schema;    
  
    public Database.Tables getTables() {
        return tables;
    }

   
    public void setTables(Database.Tables value) {
        this.tables = value;
    }

   
    public String getName() {
        return name;
    }

    
    public void setName(String value) {
        this.name = value;
    }

    
    public String getSchema() {
        return schema;
    }

   
    public void setSchema(String value) {
        this.schema = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "table"
    })
    public static class Tables {

        @XmlElement(name = "Table")
        protected List<Database.Tables.Table> table;

       
     /*   public void setTable(List<Database.Tables.Table> table) {
    		this.table = table;
    	}
        public List<Database.Tables.Table> getTable() {
            if (table == null) {
                table = new ArrayList<Database.Tables.Table>();
            }
            return this.table;
        }*/


        public List<Database.Tables.Table> getTable() {
			return table;
		}

		public void setTable(List<Database.Tables.Table> table) {
			this.table = table;
		}

		
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "field"
        })
        public static class Table {
        	
            @XmlElement(name = "Field")
            protected List<Database.Tables.Table.Field> field;
            public void setField(List<Tables.Table.Field> field) {
      			this.field = field;
      		}
            @XmlAttribute(name = "name")
            protected String name;

            public List<Database.Tables.Table.Field> getField() {
                if (field == null) {
                    field = new ArrayList<Database.Tables.Table.Field>();
                }
                return this.field;
            }

         
            public String getName() {
                return name;
            }

        
            public void setName(String value) {
                this.name = value;
            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Field {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "tablename")
                protected String tablename;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "Type")
                protected String type;
                @XmlAttribute(name = "Size")
                protected String size;

                public String getSize() {
					return size;
				}

				public void setSize(String size) {
					this.size = size;
				}

				
                public String getValue() {
                    return value;
                }

                
                public void setValue(String value) {
                    this.value = value;
                }

               
                public String getTablename() {
                    return tablename;
                }

                
                public void setTablename(String value) {
                    this.tablename = value;
                }

              
                public String getName() {
                    return name;
                }

                public void setName(String value) {
                    this.name = value;
                }

              
                public String getType() {
                    return type;
                }

               
                public void setType(String value) {
                    this.type = value;
                }

             
               

            }

        }

    }


}
